### ISSUE TITLE
Dokka documentation

### ISSUE THREAD

**Issue by xdrm-io** [SeekDaSky/Sok#1]
Hi SeekDaSky,

I am a kotlin beginner and I would like to use your library to improve my networking experience. I have seen numerous projects using [Dokka](https://github.com/Kotlin/dokka). I think it could be a great improvement  to your library.

Best regards,
XB

**Comment by SeekDaSky** [comment]
Hi,
I integrated dokka and fiddled with it a bit, I am now working on documenting every method/type/package and then I will create a github page containing the generated website. This should not take too long

**Comment by xdrm-io** [comment]
Thanks, looking forward to it.

**Comment by SeekDaSky** [comment]
There it is, a complete [documentation for Sok](https://seekdasky.github.io/SokDoc/)
Dokka is a bit outdated so it does not support some multiplatform features and unsigned types, leading to some strange errors but most of the documentation is correct.

Feel free to give some feedback

**Comment by xdrm-io** [comment]
Hi,

I've taken a brief look, it is really good and I like the design a lot. Explanations are clear and the differences between each platform is now easier for me to understand.

Thanks for your reactivity.
